### PR TITLE
Testing/2018.11.12.00

### PR DESCRIPTION
**Pull request by uilianries**
Related issue: https://github.com/bincrafters/community/issues/634

### CODE REVIEW

**Comment by SSE4** [comment]
@uilianries ping

**Comment by uilianries** [comment]
I totally forgot this one! thanks @SSE4

**Comment by uilianries** [comment]
@SSE4 same old problem with apple clang 9 and libatomic, I can't reproduce this problem, my account on Mac in Cloud only offers apple clang 10

The error occurs when liking the test_package:

`ld: library not found for -latomic`

profile:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=9.0

The full log is [here](https://travis-ci.com/bincrafters/conan-folly/jobs/192312930#L5706)

**Comment by uilianries** [comment]
Closing this one. I will try a new Folly version.

**Pull request closed without merging**
