### PR TITLE
Attempt to get 0.58.0 to build.

### PR DESCRIPTION
**Pull request by ghost**
This requires a gflags package with the `nothreads=False` option be published, but otherwise works.

### CODE REVIEW

**Comment by solvingj** [comment]
Thank you for opening this, will work on this ASAP.

**Comment by ghost** [comment]
Hey thanks, feel free to junk it if you want. Using it internally, just thought it maybe useful. Cheers!

**Comment by solvingj** [comment]
This was a priority, but everyone got busy in the spring and lots of things got stuck.also, there were some deps we were waiting on which I think are ready now:

**Comment by solvingj** [comment]
Thanks again.  I looked over your commits and applied several of your fixes, but with a few changes.  Still needs some work.  MSVC is saying 64 bit arch is required, not sure if it applies to linux/mac yet.  Also, the hacks on findlibevent are still needed for windows apparently. I should be able to push this all the way through by tomorrow eve.

**Comment by ghost** [comment]
Oh really (RE: windows builds)? I wasn't able to get the build far enough to see that. Thanks for the heads up, i'll add it back internally as well. :+1:

**Comment by ghost** [comment]
Closed as all reasonable changes have been applied to testing/0.58.0

**Pull request closed without merging**
